name: App

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to repository
        uses: actions/checkout@v4.1.1

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.15

      - name: Install Dependencies
        run: bun install --frozen-lockfile

      # Necessary because it's being used in the code
      - name: Linting/Formating
        run: bunx @biomejs/biome ci src

      - name: Build
        run: bun run build

      - name: Build Web docs
        run: bun run docs:build
